// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfiLpltBtlSqbsd1eJt5myJDN7FVDzx0Y',
    appId: '1:341639647206:web:de8729d1fc4b3db7c7d027',
    messagingSenderId: '341639647206',
    projectId: 'doggy-b482c',
    authDomain: 'doggy-b482c.firebaseapp.com',
    databaseURL: 'https://doggy-b482c-default-rtdb.firebaseio.com',
    storageBucket: 'doggy-b482c.appspot.com',
    measurementId: 'G-T30BSK6Y87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQoxJdULXzQ3gR8E00notLpixXyIXLJZA',
    appId: '1:341639647206:android:b80b6cd24040afbbc7d027',
    messagingSenderId: '341639647206',
    projectId: 'doggy-b482c',
    databaseURL: 'https://doggy-b482c-default-rtdb.firebaseio.com',
    storageBucket: 'doggy-b482c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVQdcOSRVZ0XCs_zUe2Qzw4ZUOUaVCMzM',
    appId: '1:341639647206:ios:fdd687c86075e4a9c7d027',
    messagingSenderId: '341639647206',
    projectId: 'doggy-b482c',
    databaseURL: 'https://doggy-b482c-default-rtdb.firebaseio.com',
    storageBucket: 'doggy-b482c.appspot.com',
    iosClientId: '341639647206-1ann3cjrga98d27954i1v0qrfp6jfgau.apps.googleusercontent.com',
    iosBundleId: 'com.example.doggy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVQdcOSRVZ0XCs_zUe2Qzw4ZUOUaVCMzM',
    appId: '1:341639647206:ios:fdd687c86075e4a9c7d027',
    messagingSenderId: '341639647206',
    projectId: 'doggy-b482c',
    databaseURL: 'https://doggy-b482c-default-rtdb.firebaseio.com',
    storageBucket: 'doggy-b482c.appspot.com',
    iosClientId: '341639647206-1ann3cjrga98d27954i1v0qrfp6jfgau.apps.googleusercontent.com',
    iosBundleId: 'com.example.doggy',
  );
}
